add command -> update id
vasil1y-777/lab5 pull request #21
Opened 2023-03-11 19:06 UTC by GreedlyCore

2023-03-12 18:53 UTC, vasil1y-777 requested changes

2023-03-12 18:53 UTC, vasil1y-777 commented on src/main/java/classes/commands/Update.java
> +
?

2023-03-13 17:36 UTC, GreedlyCore commented on src/main/java/classes/commands/Update.java
> +
там было исключение, которое надо было обработать, а оно исходило от 23-й строки. Уберу в следующем коммите

2023-03-13 17:58 UTC, vasil1y-777 approved these changes

2023-03-13 17:58 UTC, merged